name: 'Deploy .NET App to Azure Web App'
description: "Deploy .NET App to Azure Web App"

inputs:
  artifact_name:
    description: "Name of the artifact to be uploaded"
    required: true
  azure_web_app_name:
    description: "Name of the azure web app to deploy"
    required: true
  publish_profile:
    description: "Publish profile to be used to deploy"
    required: true
  
runs:
  using: "composite"
  steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.0.10
       with:
        # Artifact name
        name: '${{ inputs.artifact_name }}'
        path: './publish'
    
     - name: Azure WebApp
       uses: Azure/webapps-deploy@v2
       with:
        # Name of the Azure Web App
        app-name: '${{ inputs.azure_web_app_name }}'
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: '${{ inputs.publish_profile }}'
        package: './publish'