name: .NET Function Build and Deploy

on:
  push:
    branches: [ main ]
    paths: ['func-demo/**'] 
  pull_request:
    branches: [ main ]
    paths: ['func-demo/**']
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Build and publish webapi app"
      uses: ./.github/actions/build-dotnet-app
      with:
        dotnet_project_path: "./func-demo"
        dotnet_csproj_name: "func-demo.csproj"
        artifact_name: "func-demo"
  
  deploy-to-azure-func:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          # Artifact name
          name: 'func-demo'
          path: './publish'
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.4.4
        with:
      # Name of the Azure Function App
          app-name: func-dotnetblr-demo
          # Path to package or folder. *.zip or a folder to deploy
          package: './publish'
          # Publish profile (*.publishsettings) file contents with web deploy secrets
          publish-profile: ${{ secrets.AZURE_FUNC_PUBLISH_PROFILE }}